name: Bug Report
description: Report something that's not working correctly
labels: ["kind/bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! You can also ask questions on our [Community Slack](https://slack.pulumi.com/).
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What were you trying to accomplish? What did you expect to happen? Which resources are involved?
    validations:
      required: true
  - type: textarea
    id: reproducible
    attributes:
      label: Example
      description: |
        Provide a link or inline code along with a clear set of steps to reproduce this bug.
    validations:
      required: true
  - type: textarea
    id: versions
    attributes:
      label: Output of `pulumi about`
      description: Provide the output of `pulumi about` from the root of your project. We need to know which versions of runtimes & plugins you're using.
    validations:
      required: true
  - type: textarea
    id: ctx
    attributes:
      label: Additional context
      description: Anything else you would like to add?
    validations:
      required: false
  - type: textarea
    id: voting
    attributes:
      label: Contributing
      value: |
        Vote on this issue by adding a 👍 reaction. 
        To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already). 
